import { useState } from 'react';
import './styles/optimized-image.css';

function slugify(input: string) {
  return String(input)
    .toLowerCase()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-_]/g, '-')
    .replace(/--+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function deriveSlugFromSrc(src: string) {
  if (!src) return '';
  // If the caller provides a public path like /images/foo.jpg, extract base
  try {
    const url = new URL(src, 'http://example.com');
    const pathname = url.pathname;
    const name = pathname.split('/').pop() || pathname;
    return slugify(name.replace(/\.[^/.]+$/, ''));
  } catch {
    // fallback for plain filenames
    const name = src.split('/').pop() || src;
    return slugify(name.replace(/\.[^/.]+$/, ''));
  }
}

interface SimpleImageProps {
  src: string;
  alt: string;
  className?: string;
  loading?: 'lazy' | 'eager';
  objectFit?: 'cover' | 'contain' | 'fill' | 'none' | 'scale-down';
  priority?: boolean;
  aspectRatio?: string;
  fallbackSrc?: string;
}

/**
 * Simplified image component with loading states and error handling
 * Replaces the over-engineered OptimizedImage component
 */
export default function SimpleImage({
  src,
  alt,
  className = '',
  loading = 'lazy',
  objectFit = 'cover',
  priority = false,
  aspectRatio,
  fallbackSrc
}: SimpleImageProps) {

  const [isLoaded, setIsLoaded] = useState(false);
  const [hasError, setHasError] = useState(false);
  
  const containerStyle: React.CSSProperties = {
    position: 'relative',
    width: '100%',
    height: '100%',
    ...(aspectRatio && { aspectRatio })
  };

  const imageStyle: React.CSSProperties = {
    width: '100%',
    height: '100%',
    objectFit,
    opacity: isLoaded ? 1 : 0,
    transition: 'opacity 0.3s ease'
  };
  const handleLoad = () => {
    setIsLoaded(true);
  };

  const handleError = () => {
    setHasError(true);
  };

  // derive public image base (no size suffix) using slug convention
  const slug = deriveSlugFromSrc(src);
  const publicBase = slug ? `/images/${slug}` : src;
  const avif = `${publicBase}.avif`;
  const webp = `${publicBase}.webp`;
  const jpg = `${publicBase}.jpg`;

  // Last-resort fallback served from public/images generated by the script
  const defaultProjectsFallback = '/images/projects-fallback.jpg';
  const finalFallback = fallbackSrc ?? defaultProjectsFallback;

  return (
    <div className={`image-container ${className}`} style={containerStyle}>
      {!isLoaded && !hasError && (
        <div className="image-loading" aria-hidden="true">
          <div className="loading-skeleton" />
        </div>
      )}
      
      <picture>
        <source srcSet={avif} type="image/avif" />
        <source srcSet={webp} type="image/webp" />
        <img
          src={hasError ? finalFallback : jpg}
          alt={alt}
          loading={priority ? 'eager' : loading}
          style={imageStyle}
          onLoad={handleLoad}
          onError={handleError}
          decoding="async"
        />
      </picture>
      
      {hasError && !finalFallback && (
        <div className="image-error" aria-hidden="true">
          <span>Image failed to load</span>
        </div>
      )}
    </div>
  );
}

// Export for backward compatibility
export const imageSizes = {
  hero: '100vw',
  card: '(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw',
  thumbnail: '150px',
  full: '100vw',
  project: '(max-width: 40em) 100vw, (max-width: 64em) 80vw, 800px'
} as const;

// Legacy export
export { SimpleImage as OptimizedImage };