import { useState } from 'react';
import './styles/optimized-image.css';
import { deriveSlugFromSrc } from '@/components/global/imageUtils';

interface SimpleImageProps {
  src: string;
  alt: string;
  className?: string;
  loading?: 'lazy' | 'eager';
  objectFit?: 'cover' | 'contain' | 'fill' | 'none' | 'scale-down';
  objectPosition?: 'top' | 'bottom' | 'left' | 'right' | 'center' | 'top left' | 'top right' | 'bottom left' | 'bottom right';
  priority?: boolean;
  aspectRatio?: string;
  fallbackSrc?: string;
}

/**
 * Simplified image component with loading states and error handling
 * Replaces the over-engineered OptimizedImage component
 */
export default function SimpleImage({
  src,
  alt,
  className = '',
  loading = 'lazy',
  objectFit = 'cover',
  objectPosition='center',
  priority = false,
  aspectRatio,
  fallbackSrc
}: SimpleImageProps) {

  const [isLoaded, setIsLoaded] = useState(false);
  const [hasError, setHasError] = useState(false);
  
  const containerStyle: React.CSSProperties = {
    position: 'relative',
    width: '100%',
    height: '100%',
    ...(aspectRatio && { aspectRatio })
  };

  const imageStyle: React.CSSProperties = {
    width: '100%',
    height: '100%',
    objectFit,
    objectPosition,
    opacity: isLoaded ? 1 : 0,
    transition: 'opacity 0.3s ease'
  };
  const handleLoad = () => {
    setIsLoaded(true);
  };

  const handleError = () => {
    setHasError(true);
  };

  // derive public image base (no size suffix) using slug convention
  const slug = deriveSlugFromSrc(src);
  const publicBase = slug ? `/images/${slug}` : src;
  const avif = `${publicBase}.avif`;
  const webp = `${publicBase}.webp`;
  const jpg = `${publicBase}.jpg`;

  // Last-resort fallback served from public/images generated by the script
  const defaultProjectsFallback = '/images/fallback.jpg';
  const finalFallback = fallbackSrc ?? defaultProjectsFallback;

  return (
    <span className={`image-container ${className}`} style={containerStyle}>
      {!isLoaded && !hasError && (
        <span className="image-loading" aria-hidden="true">
          <span className="loading-skeleton" />
        </span>
      )}
      
      <picture>
        <source srcSet={avif} type="image/avif" />
        <source srcSet={webp} type="image/webp" />
        <img
          src={hasError ? finalFallback : jpg}
          alt={alt}
          loading={priority ? 'eager' : loading}
          style={imageStyle}
          onLoad={handleLoad}
          onError={handleError}
          decoding="async"
        />
      </picture>
      
      {hasError && !finalFallback && (
        <span className="image-error" aria-hidden="true">
          <span>Image failed to load</span>
        </span>
      )}
    </span>
  );
}

// Legacy export
export { SimpleImage as OptimizedImage };